### PR TITLE
Remove "GitExtensions" sub folder from `GitExtensionsPath`

### PR DESCRIPTION
**Pull request by maraf**
It seems that zip bundling has changed in v4 and the zip file doesn't contain single root folder "GitExtensions" anymore

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Comment by RussKie** [comment]
...long story short, but this change is incomplete. E.g., this [build](https://ci.appveyor.com/project/gitextensions/gitextensions-pluginmanager/builds/48609909) is failing.

```
...
  Extraction root path is 'C:\projects\gitextensions.shared'.
  Searching for Git Extensions release 'latest' on 'AppVeyor'.
  Selected build job '7gm8u3luiu82vcbf'.
  Selected asset 'artifacts/Release/publish/GitExtensions-Portable-4.3.0.17607-291c6d1c3.zip'.
  Downloading 'https://ci.appveyor.com/api/buildjobs/7gm8u3luiu82vcbf/artifacts/artifacts/Release/publish/GitExtensions-Portable-4.3.0.17607-291c6d1c3.zip'...
  Application extracted to 'C:\projects\gitextensions.shared\GitExtensions'.
  PackageManager -> C:\projects\gitextensions-pluginmanager\src\PackageManager\bin\Release\net8.0-windows\PackageManager.dll
  PackageManager.NuGet -> C:\projects\gitextensions-pluginmanager\src\PackageManager.NuGet\bin\Release\net8.0-windows\PackageManager.NuGet.dll
  PackageManager.UI -> C:\projects\gitextensions-pluginmanager\src\PackageManager.UI\bin\Release\net8.0-windows\win-x86\PackageManager.UI.dll
C:\Program Files\dotnet\sdk\8.0.100\Microsoft.Common.CurrentVersion.targets(2382,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "GitUI". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\gitextensions-pluginmanager\src\GitExtensions.PluginManager\GitExtensions.PluginManager.csproj]
```


This change (introduced in #21) had to be rolled back as well:
https://github.com/gitextensions/gitextensions.extensibility/blob/e467de328d7616fd4507f961fcfd5b20cc742d37/src/GitExtensions.Extensibility/tools/Download-GitExtensions.ps1#L177-L180
